### ISSUE TITLE
Impl `Invoke-WebRequest`

### ISSUE THREAD

**Issue by LiaNdrY** [steve02081504/ps12exe#1]
### 检查清单 Prerequisites

- [X] 请确保你已经检索了已关闭的问题，以确保你的问题没有被重复提交
Make sure you have retrieved closed issues to make sure your issue has not been submitted repeatedly

### 问题描述
Problem description

When trying to read a string, for example this:

`$Ver = (Invoke-WebRequest -Uri 'https://sdk.lunarg.com/sdk/download/latest/windows/config.json' -UseBasicParsing | ConvertFrom-Json).version`

exe file displays in the console "**ERROR: Method or operation not implemented.**" Although there is no problem with a simple launch via PowerShell.

### 解决方案描述
Solution description

Add this functionality

### 替代方案描述
Alternative description

_No response_

### 附加内容
Additional context

_No response_

**Comment by steve02081504** [comment]
```text
~ >"(Invoke-WebRequest -Uri 'https://sdk.lunarg.com/sdk/download/latest/windows/config.json' -UseBasicParsing | ConvertFrom-Json).version" | ps12exe
Compiled file written -> 23552 bytes
~ >./a.exe
ERROR: 未实现该方法或操作。
~ >"Invoke-WebRequest -Uri 'https://sdk.lunarg.com/sdk/download/latest/windows/config.json'" | ps12exe
Compiled file written -> 23552 bytes
~ >./a.exe
ERROR: 未实现该方法或操作。
~ >'"{}"|ConvertFrom-Json' | ps12exe
Compiled file written -> 23552 bytes
~ >./a.exe

~ >
```
Maybe it's a question about `Invoke-WebRequest` (and constexpr chaeck with `ConvertFrom-Json` lol)
I'll try to deal with it sometime

**Comment by steve02081504** [comment]
fixed at https://github.com/steve02081504/ps12exe/releases/tag/v0.1.27
thx for report!
