### ISSUE TITLE
exe无法在win7、.net3.5支持

### ISSUE THREAD

**Issue by Copperfie1d** [steve02081504/ps12exe#15]
ps2exe能编译，但运行无法达到预期，会考虑适配.net 3.5吗 :）

**Comment by steve02081504** [comment]
我不清楚如何适配它，如果你有任何想法或思路欢迎留言或提交pr？

**Comment by steve02081504** [comment]
https://github.com/steve02081504/ps12exe/releases/tag/v0.3.46
用 powershell 2.0 语法和 `ps12exe -targetRuntime 'Framework2.0'` 来编译支持win7和.net3.5的exe
