### ISSUE TITLE
Failing to load the language when en-US

### ISSUE THREAD

**Issue by ennioVisco** [steve02081504/ps12exe#17]
### 检查清单 Prerequisites

- [X] 请确保你是在最新版本中遇见此问题
Make sure you have this bug in the latest release
- [X] 请确保你已经检索了已关闭的问题，以确保你的问题没有被重复提交
Make sure you have retrieved closed issues to make sure your issue has not been submitted repeatedly

### 描述错误
Describe the bug

I guess the issue is related to the fact that en-US is the default, so perhaps the warning should just not be triggered when the language is `en-US`...

### 复现
To Reproduce

use a pc with en-US locale set.

### 预期行为
Expected behavior

No warning should appear.

### 截图
Screenshots

![image](https://github.com/user-attachments/assets/11b1a2d0-f29a-4e89-8f8a-28e541e4e2eb)

### 附加上下文
Additional context

_No response_

**Comment by steve02081504** [comment]
The English locale in ps12exe is en-UK, so strictly this is a normal alarm.
I'll try to add a locale in American English in the next version.

**Comment by steve02081504** [comment]
en-US locale added in [`v0.5.4`](https://www.powershellgallery.com/packages/ps12exe/0.5.4)
leeme konw if there's sth worng :)

**Comment by nigz891** [comment]
I'm getting this every time I open it and have followed the instructions in the readme.md, but there is no need to edit any fsb and en-uk is in the locale folder.  My pc is also set to en-uk, although I'm not in the uk.  

![Image](https://github.com/user-attachments/assets/90964392-6e99-4add-8a2a-19041c346974)
![Image](https://github.com/user-attachments/assets/1d83f6b5-fe20-4f55-9221-2cf4756f12d1)
